# Generated by Django 3.0.6 on 2020-08-03 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('img1', models.ImageField(upload_to='images')),
                ('img2', models.ImageField(upload_to='images')),
                ('img3', models.ImageField(upload_to='images')),
                ('img4', models.ImageField(upload_to='images')),
                ('img5', models.ImageField(upload_to='images')),
                ('text1', models.TextField(default='')),
                ('text2', models.TextField(default='')),
                ('text3', models.TextField(default='')),
                ('text4', models.TextField(default='')),
                ('text5', models.TextField(default='')),
                ('lattitude', models.TextField()),
                ('longitude', models.TextField()),
            ],
        ),
    ]
